# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../interface/ui_files/admin_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MW_admin(object):
    def setupUi(self, MW_admin):
        MW_admin.setObjectName("MW_admin")
        MW_admin.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MW_admin)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 20, 151, 51))
        self.pushButton.setObjectName("pushButton")
        MW_admin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MW_admin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MW_admin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MW_admin)
        self.statusbar.setObjectName("statusbar")
        MW_admin.setStatusBar(self.statusbar)

        self.retranslateUi(MW_admin)
        QtCore.QMetaObject.connectSlotsByName(MW_admin)

    def retranslateUi(self, MW_admin):
        _translate = QtCore.QCoreApplication.translate
        MW_admin.setWindowTitle(_translate("MW_admin", "MainWindow"))
        self.pushButton.setText(_translate("MW_admin", "Добавить врача"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MW_admin = QtWidgets.QMainWindow()
    ui = Ui_MW_admin()
    ui.setupUi(MW_admin)
    MW_admin.show()
    sys.exit(app.exec_())
