# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../interface/ui_files/doctor_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MW_doctor(object):
    def setupUi(self, MW_doctor):
        MW_doctor.setObjectName("MW_doctor")
        MW_doctor.resize(441, 222)
        self.centralwidget = QtWidgets.QWidget(MW_doctor)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_start_reception = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start_reception.setGeometry(QtCore.QRect(140, 90, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_start_reception.setFont(font)
        self.pushButton_start_reception.setObjectName("pushButton_start_reception")
        self.label_doctor_data = QtWidgets.QLabel(self.centralwidget)
        self.label_doctor_data.setGeometry(QtCore.QRect(10, 10, 421, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_doctor_data.setFont(font)
        self.label_doctor_data.setStyleSheet("background-color: rgb(170, 170, 0);\n"
"border-radius: 10px;")
        self.label_doctor_data.setAlignment(QtCore.Qt.AlignCenter)
        self.label_doctor_data.setObjectName("label_doctor_data")
        MW_doctor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MW_doctor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 441, 21))
        self.menubar.setObjectName("menubar")
        MW_doctor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MW_doctor)
        self.statusbar.setObjectName("statusbar")
        MW_doctor.setStatusBar(self.statusbar)

        self.retranslateUi(MW_doctor)
        QtCore.QMetaObject.connectSlotsByName(MW_doctor)

    def retranslateUi(self, MW_doctor):
        _translate = QtCore.QCoreApplication.translate
        MW_doctor.setWindowTitle(_translate("MW_doctor", "MainWindow"))
        self.pushButton_start_reception.setText(_translate("MW_doctor", "Начать приём"))
        self.label_doctor_data.setText(_translate("MW_doctor", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MW_doctor = QtWidgets.QMainWindow()
    ui = Ui_MW_doctor()
    ui.setupUi(MW_doctor)
    MW_doctor.show()
    sys.exit(app.exec_())
