# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../interface/ui_files/doctor_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MW_doctor(object):
    def setupUi(self, MW_doctor):
        MW_doctor.setObjectName("MW_doctor")
        MW_doctor.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MW_doctor)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 40, 141, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 160, 151, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 50, 161, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 160, 371, 71))
        self.pushButton_4.setObjectName("pushButton_4")
        MW_doctor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MW_doctor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MW_doctor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MW_doctor)
        self.statusbar.setObjectName("statusbar")
        MW_doctor.setStatusBar(self.statusbar)

        self.retranslateUi(MW_doctor)
        QtCore.QMetaObject.connectSlotsByName(MW_doctor)

    def retranslateUi(self, MW_doctor):
        _translate = QtCore.QCoreApplication.translate
        MW_doctor.setWindowTitle(_translate("MW_doctor", "MainWindow"))
        self.pushButton.setText(_translate("MW_doctor", "Начать приём"))
        self.pushButton_3.setText(_translate("MW_doctor", "Посмотреть мой участок"))
        self.pushButton_2.setText(_translate("MW_doctor", "редактировать приём"))
        self.pushButton_4.setText(_translate("MW_doctor", "посмотреть историю приёмов пациента у специалиста"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MW_doctor = QtWidgets.QMainWindow()
    ui = Ui_MW_doctor()
    ui.setupUi(MW_doctor)
    MW_doctor.show()
    sys.exit(app.exec_())
