# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../interface/ui_files/history_receptions.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_history_receptions(object):
    def setupUi(self, Form_history_receptions):
        Form_history_receptions.setObjectName("Form_history_receptions")
        Form_history_receptions.resize(891, 342)
        self.tableWidget_h_r = QtWidgets.QTableWidget(Form_history_receptions)
        self.tableWidget_h_r.setGeometry(QtCore.QRect(5, 11, 881, 321))
        self.tableWidget_h_r.setObjectName("tableWidget_h_r")
        self.tableWidget_h_r.setColumnCount(0)
        self.tableWidget_h_r.setRowCount(0)

        self.retranslateUi(Form_history_receptions)
        QtCore.QMetaObject.connectSlotsByName(Form_history_receptions)

    def retranslateUi(self, Form_history_receptions):
        _translate = QtCore.QCoreApplication.translate
        Form_history_receptions.setWindowTitle(_translate("Form_history_receptions", "История приемов"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_history_receptions = QtWidgets.QWidget()
    ui = Ui_Form_history_receptions()
    ui.setupUi(Form_history_receptions)
    Form_history_receptions.show()
    sys.exit(app.exec_())
