# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../interface/ui_files/history_receptions.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_history_receptions(object):
    def setupUi(self, Form_history_receptions):
        Form_history_receptions.setObjectName("Form_history_receptions")
        Form_history_receptions.resize(972, 471)
        self.tableWidget_h_r = QtWidgets.QTableWidget(Form_history_receptions)
        self.tableWidget_h_r.setGeometry(QtCore.QRect(10, 80, 951, 321))
        self.tableWidget_h_r.setObjectName("tableWidget_h_r")
        self.tableWidget_h_r.setColumnCount(0)
        self.tableWidget_h_r.setRowCount(0)
        self.pushButton_select_history = QtWidgets.QPushButton(Form_history_receptions)
        self.pushButton_select_history.setGeometry(QtCore.QRect(770, 10, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_history.setFont(font)
        self.pushButton_select_history.setObjectName("pushButton_select_history")
        self.widget = QtWidgets.QWidget(Form_history_receptions)
        self.widget.setGeometry(QtCore.QRect(270, 10, 274, 56))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_date_range = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_date_range.setFont(font)
        self.label_date_range.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date_range.setObjectName("label_date_range")
        self.verticalLayout.addWidget(self.label_date_range)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_start_date = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_start_date.setFont(font)
        self.label_start_date.setObjectName("label_start_date")
        self.horizontalLayout_2.addWidget(self.label_start_date)
        self.dateEdit_start_date = QtWidgets.QDateEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit_start_date.setFont(font)
        self.dateEdit_start_date.setObjectName("dateEdit_start_date")
        self.horizontalLayout_2.addWidget(self.dateEdit_start_date)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_end_date = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_end_date.setFont(font)
        self.label_end_date.setObjectName("label_end_date")
        self.horizontalLayout.addWidget(self.label_end_date)
        self.dateEdit_end_date = QtWidgets.QDateEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit_end_date.setFont(font)
        self.dateEdit_end_date.setObjectName("dateEdit_end_date")
        self.horizontalLayout.addWidget(self.dateEdit_end_date)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.widget1 = QtWidgets.QWidget(Form_history_receptions)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 181, 52))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_spec_d = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_spec_d.setFont(font)
        self.label_spec_d.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spec_d.setObjectName("label_spec_d")
        self.verticalLayout_2.addWidget(self.label_spec_d)
        self.comboBox_spec_d = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_spec_d.setFont(font)
        self.comboBox_spec_d.setObjectName("comboBox_spec_d")
        self.verticalLayout_2.addWidget(self.comboBox_spec_d)

        self.retranslateUi(Form_history_receptions)
        QtCore.QMetaObject.connectSlotsByName(Form_history_receptions)

    def retranslateUi(self, Form_history_receptions):
        _translate = QtCore.QCoreApplication.translate
        Form_history_receptions.setWindowTitle(_translate("Form_history_receptions", "История приемов"))
        self.pushButton_select_history.setText(_translate("Form_history_receptions", "Вывести историю"))
        self.label_date_range.setText(_translate("Form_history_receptions", "Диапазон дат"))
        self.label_start_date.setText(_translate("Form_history_receptions", "С"))
        self.label_end_date.setText(_translate("Form_history_receptions", "До"))
        self.label_spec_d.setText(_translate("Form_history_receptions", "Специализация:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_history_receptions = QtWidgets.QWidget()
    ui = Ui_Form_history_receptions()
    ui.setupUi(Form_history_receptions)
    Form_history_receptions.show()
    sys.exit(app.exec_())
