# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../interface/ui_files/patient_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MW_patient(object):
    def setupUi(self, MW_patient):
        MW_patient.setObjectName("MW_patient")
        MW_patient.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MW_patient)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_see_edit_data = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_see_edit_data.setGeometry(QtCore.QRect(10, 80, 151, 51))
        self.pushButton_see_edit_data.setObjectName("pushButton_see_edit_data")
        self.pushButton_get_ticket = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_get_ticket.setGeometry(QtCore.QRect(10, 230, 121, 41))
        self.pushButton_get_ticket.setObjectName("pushButton_get_ticket")
        self.pushButton_get_reception = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_get_reception.setGeometry(QtCore.QRect(150, 230, 141, 41))
        self.pushButton_get_reception.setObjectName("pushButton_get_reception")
        self.label_welcome_p = QtWidgets.QLabel(self.centralwidget)
        self.label_welcome_p.setGeometry(QtCore.QRect(10, 10, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_welcome_p.setFont(font)
        self.label_welcome_p.setStyleSheet("background-color: rgb(155, 217, 255);\n"
"border-radius: 10px;")
        self.label_welcome_p.setAlignment(QtCore.Qt.AlignCenter)
        self.label_welcome_p.setObjectName("label_welcome_p")
        self.pushButton_book_ticket = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_book_ticket.setGeometry(QtCore.QRect(160, 150, 121, 51))
        self.pushButton_book_ticket.setStyleSheet("background-color: rgb(94, 89, 255);")
        self.pushButton_book_ticket.setAutoDefault(False)
        self.pushButton_book_ticket.setDefault(False)
        self.pushButton_book_ticket.setFlat(False)
        self.pushButton_book_ticket.setObjectName("pushButton_book_ticket")
        self.pushButton_get_area = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_get_area.setGeometry(QtCore.QRect(280, 80, 141, 51))
        self.pushButton_get_area.setObjectName("pushButton_get_area")
        MW_patient.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MW_patient)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MW_patient.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MW_patient)
        self.statusbar.setObjectName("statusbar")
        MW_patient.setStatusBar(self.statusbar)

        self.retranslateUi(MW_patient)
        QtCore.QMetaObject.connectSlotsByName(MW_patient)

    def retranslateUi(self, MW_patient):
        _translate = QtCore.QCoreApplication.translate
        MW_patient.setWindowTitle(_translate("MW_patient", "Окно для работы пациента"))
        self.pushButton_see_edit_data.setText(_translate("MW_patient", "Просмотреть мои данные"))
        self.pushButton_get_ticket.setText(_translate("MW_patient", "Просмотреть талоны"))
        self.pushButton_get_reception.setText(_translate("MW_patient", "Просмотреть приёмы"))
        self.label_welcome_p.setText(_translate("MW_patient", "Добро пожаловать, ФИО пациента"))
        self.pushButton_book_ticket.setText(_translate("MW_patient", "Взять талон"))
        self.pushButton_get_area.setText(_translate("MW_patient", "Посмотреть мой участок"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MW_patient = QtWidgets.QMainWindow()
    ui = Ui_MW_patient()
    ui.setupUi(MW_patient)
    MW_patient.show()
    sys.exit(app.exec_())
