# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../interface/ui_files/patient_taken_tickets.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_patient_taken_tickets(object):
    def setupUi(self, Form_patient_taken_tickets):
        Form_patient_taken_tickets.setObjectName("Form_patient_taken_tickets")
        Form_patient_taken_tickets.resize(812, 341)
        self.tableWidget_taken_tickets = QtWidgets.QTableWidget(Form_patient_taken_tickets)
        self.tableWidget_taken_tickets.setGeometry(QtCore.QRect(10, 10, 791, 321))
        self.tableWidget_taken_tickets.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_taken_tickets.setObjectName("tableWidget_taken_tickets")
        self.tableWidget_taken_tickets.setColumnCount(0)
        self.tableWidget_taken_tickets.setRowCount(0)

        self.retranslateUi(Form_patient_taken_tickets)
        QtCore.QMetaObject.connectSlotsByName(Form_patient_taken_tickets)

    def retranslateUi(self, Form_patient_taken_tickets):
        _translate = QtCore.QCoreApplication.translate
        Form_patient_taken_tickets.setWindowTitle(_translate("Form_patient_taken_tickets", "Просмотр взятых талонов на прием"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_patient_taken_tickets = QtWidgets.QWidget()
    ui = Ui_Form_patient_taken_tickets()
    ui.setupUi(Form_patient_taken_tickets)
    Form_patient_taken_tickets.show()
    sys.exit(app.exec_())
